version: '3'
services:
  neo4j-db:
      image: neo4j:3.4.0
      volumes:
          - $PWD/Graph/data:/var/lib/neo4j/data
          - $PWD/import:/var/lib/neo4j/import
      environment:
          - NEO4J_AUTH=neo4j/somepassword
  webapp:
      image: china-unicorn-index
      build: .
      ports:
          - "33838:3838"
      volumes:
          - $PWD/config.yml:/srv/shiny-server/china-unicorn-index/config.yml
